### ISSUE TITLE
Depend on "basic-lens" for lenses

### ISSUE THREAD

**Issue by nikita-volkov** [Soostone/uri-bytestring#17]
http://hackage.haskell.org/package/basic-lens

Pinging @chrisdone

**Comment by chrisdone** [comment]
:+1: Good idea, that'd make the type signatures easier to read.

**Comment by MichaelXavier** [comment]
A coworker talked to Edward Kmett about this and he had a pretty nice solution: define an unexported type alias in the module. Haddocks will pick it up but it won't require a dependency and will still be readable. For instance, he does this with `Iso` [here](http://hackage.haskell.org/package/profunctors-5.1.1/docs/src/Data-Profunctor-Rep.html#Rep). If its all the same I think I may just do that.

**Comment by chrisdone** [comment]
Unexported types are the work of the devil, but if you're happy with it feel free.

**Comment by mightybyte** [comment]
Care to elaborate?  This would be an alias...

**Comment by MichaelXavier** [comment]
Yeah it seems to me like it would achieve the same goal but it just wouldn't let you click through to what a lens is.  I think if you know you need a lens, you know what it is when you see `Lens`. If you see the big long type in the haddocks like you do right now, you could be forgiven to have no idea what it is. So the only thing we're missing out on is a link to the basic-lens package.
