### ISSUE TITLE
Problem with parsing URL containing %-encodings

### ISSUE THREAD

**Issue by zkf** [Soostone/uri-bytestring#20]
Am I doing something wrong here? I don't understand why the %-encoded space `%20` in the path is re-encoded as `%2520`. 
```
Prelude URI.ByteString> serializeURI' <$> parseURI laxURIParserOptions "http://www.example.com/weird%20path"
Right "http://www.example.com/weird%2520path"
```
Sorry if this is an obvious mistake on my part.

**Comment by MichaelXavier** [comment]
Nice find. This should fix it.
