### ISSUE TITLE
Provide tools to work with URI-references

### ISSUE THREAD

**Issue by k0ral** [Soostone/uri-bytestring#23]
It's nice that the library makes it possible to distinguish between `URI`s and `RelativeRef`s, but in many cases I simply want to parse/serialize any of them, without bothering with the distinction.
The RFC 3986 defines _URI-references_ for that (cf §4.1):

```
URI-reference is used to denote the most common usage of a resource identifier.

   URI-reference = URI / relative-ref
```

It would be nice to implement _URI-references_ and provide related tools.

**Comment by seagreen** [comment]
1st: Holy smoke, `uri-bytestring` is awesome! Thanks for the library.

2nd: No rush, but I would find this useful as well. Right now I'm using my own custom datatype:

```
data URI                                                                                                                     
    = URIAbsolute (URI.URIRef URI.Absolute)                                                                                  
    | URIRelative (URI.URIRef URI.Relative)                                                                                  
    deriving (Eq, Show)
```
... but that's obviously too simplistic to go in `uri-bytestring`. Perhaps as well as `RelativeRef` and `URI`, `URI.ByteString` could provide another constructor for `URIRef`s that's exactly like `URI` except instead of `uriScheme :: Scheme` it has `fooScheme :: Maybe Scheme`?

**Comment by seagreen** [comment]
Wait, I'm confused. I see now hold old this issue is, and the a PR related to it is already merged. With the current version of the library is there a way to parse a bytestring to either a `URIRef Absolute` or a `URIRef Relative`? If there is I'm totally missing it.

**Comment by MichaelXavier** [comment]
Yeah I think this ticket is meant to be closed. Check out https://hackage.haskell.org/package/uri-bytestring-0.2.2.1/docs/URI-ByteString.html#g:3 and `parseRelativeRef`and `parseURI`.

**Comment by seagreen** [comment]
Gotchya. It seem like while the library now supports parsing to either a relative or absolute reference as two separate things, there's no datatype provided (or parsing function to use) when you don't know which you're dealing with and want to support both.

It seems like this will come up a lot. Want me to make a separate issue for it?

**Comment by MichaelXavier** [comment]
If you think it would be useful I don't have any objection to adding it, but it isn't entirely clear to me what its type should be nor its semantics. You'd need a return type that covered an error and the cases of relative or absolute. Which should it try first? Which error should it ultimately return if both parses fail? Right now its just 2 either functions so the user can easily use Either's Alternative, simple case statements, etc to define the behavior on failure.

**Comment by seagreen** [comment]
Sounds good. I'll explore things some more, and if I come up with a concrete suggestion I'll open a new issue for it.
