### ISSUE TITLE
Compatibility with semigroups-0.17

### ISSUE THREAD

**Issue by DanBurton** [Soostone/uri-bytestring#24]
I realize that the .cabal file says:

> void currently breaks with semigroups 0.17

I don't really understand what this means, but uri-bytestring is the only package on stackage that isn't compatible with semigroups-0.17. Can something be done about this?

**Comment by MichaelXavier** [comment]
There was an issue where semigroups 0.17 would not compile with the `void` package that made our dependency tree unusable with semigroups >= 0.17. I see that 0.17.1 is out so I'll see if that builds.

**Comment by MichaelXavier** [comment]
0.1.9.1 just put up on hackage, removes the limit. I don't know why travis isn't building it but the tests build on my machine. Let me know if there are any issues.
