### ISSUE TITLE
Unable to parse SSH URI scheme format

### ISSUE THREAD

**Issue by iand675** [Soostone/uri-bytestring#25]
I know that currently uri-bytestring is only explicitly supporting RFC3986 at the moment, but is there any chance of the library offering support for other URI formats such as the ones outlined for SSH & SFTP URIs? https://tools.ietf.org/html/draft-ietf-secsh-scp-sftp-ssh-uri-04

**Comment by iand675** [comment]
For a bit more context, the URIs that aren't parsing are the ones provided by GitHub if you're using SSH to clone: e.g. `git@github.com:Soostone/uri-bytestring.git`. I was under the impression that this was considered to be an SSH URI, but the syntax may be a bit different...

**Comment by MichaelXavier** [comment]
I wasn't really expecting it to work but interestingly enough, uri-bytestring works for varying definition of "works" for the examples in the SSH/SFTP document you linked:

```haskell
λ> parseURI laxURIParserOptions "ssh://user@host.example.com"
Right (URI {uriScheme = Scheme {schemeBS = "ssh"}, uriAuthority = Just (Authority {authorityUserInfo = Just (UserInfo {uiUsername = "user", uiPassword = ""}), authorityHost = Host {hostBS = "host.example.com"}, authorityPort = Nothing}), uriPath = "", uriQuery = Query {queryPairs = []}, uriFragment = Nothing})
λ> parseURI laxURIParserOptions "ssh://user@host.example.com/~/file.txt"
Right (URI {uriScheme = Scheme {schemeBS = "ssh"}, uriAuthority = Just (Authority {authorityUserInfo = Just (UserInfo {uiUsername = "user", uiPassword = ""}), authorityHost = Host {hostBS = "host.example.com"}, authorityPort = Nothing}), uriPath = "/~/file.txt", uriQuery = Query {queryPairs = []}, uriFragment = Nothing})
λ> parseURI laxURIParserOptions "ssh://user;fingerprint=ssh-dss-c1-b1-30-29-d7-b8-de-6c-97-77-10-d7-46-41-63-87@host.example.com"
Right (URI {uriScheme = Scheme {schemeBS = "ssh"}, uriAuthority = Just (Authority {authorityUserInfo = Just (UserInfo {uiUsername = "user;fingerprint=ssh-dss-c1-b1-30-29-d7-b8-de-6c-97-77-10-d7-46-41-63-87", uiPassword = ""}), authorityHost = Host {hostBS = "host.example.com"}, authorityPort = Nothing}), uriPath = "", uriQuery = Query {queryPairs = []}, uriFragment = Nothing})
```

So those are fine. The git URI I think only resembles URIs superficially. The part that trips it is up is `:Soostone`. The spec says the thing after the `:` but before the `/` must be a port, which must be `*DIGIT`. So even if I changed the parser to support this, I'd have to type change Port from an Int to a ByteString and it would just be super weird to have a URI with host github.com and port "Soostone". I think this would also open the door to parsing things that resemble URIs in this library which I don't think I can justify. My recommendation would be to either use the HTTPS git URIs if possible (those should parse) or to write your own regex/(atto)?parsec parser for the special case of git addresses.
