### ISSUE TITLE
URI normalization

### ISSUE THREAD

**Issue by bitemyapp** [Soostone/uri-bytestring#27]
Currently `network-uri` doesn't implement [RFC 3986 6.2.3](https://tools.ietf.org/html/rfc3986#section-6.2.3), so even if we didn't care about perf, we don't have a complete solution for this. Seems like an appropriate feature so putting this up in case anyone else notices & cares.

**Comment by MichaelXavier** [comment]
@bitemyapp So what are you looking for in normalization, generally. The RFC seems mostly concerned with equivalence. Are you looking for a serialization function like `URI -> ByteString` that produces a consistent, fully-expanded string? Like a uri parsed from `http://google.com` would produce `http://google.com:80/`?

**Comment by bitemyapp** [comment]
@MichaelXavier I think I'd normalize to the minimal representation in this case, only leaving in information that isn't the default.

**Comment by MichaelXavier** [comment]
@bitemyapp At long last I took a crack at this. I tried to include as many of the suggested normalizations from the RFC as possible. Check out the [27-normalization](https://github.com/Soostone/uri-bytestring/tree/27-normalization) branch. I tacked normalization as a special case of serialization (or rather made the existing serialization functions use the normalizing functions with all normalizations disabled). You'll want to look at `normalizeURIRef`. Let me know what you think when you get a chance.

**Comment by bitemyapp** [comment]
@MichaelXavier thank you! I'll be looking at this this week :)

**Comment by MichaelXavier** [comment]
@bitemyapp how did this go?

**Comment by bitemyapp** [comment]
@MichaelXavier I kicked it around and it seemed fine, but we'd already moved on from that task so I haven't tried it in "anger", sorry!

**Comment by MichaelXavier** [comment]
Released!
