### ISSUE TITLE
Relax upper bound of base on hackage

### ISSUE THREAD

**Issue by k0ral** [Soostone/uri-bytestring#29]
As per 21c7190265ec76f866fbc9853583c598c94be1de, upper bound of `base` was updated to `< 4.10`, however [it's still set to `< 4.9` on hackage][1].
Could you please update the hackage release accordingly ?

Thank you.

[1]: http://hackage.haskell.org/package/uri-bytestring

**Comment by MichaelXavier** [comment]
Uploaded at 0.2.1.0.
