### ISSUE TITLE
metadata on hackage contains strange links

### ISSUE THREAD

**Issue by mf59816** [Soostone/uri-bytestring#3]
https://hackage.haskell.org/package/uri-bytestring

    Home page	https://travis-ci.org/Soostone/uri-bytestring 
    Bug tracker	https://travis-ci.org/Soostone/uri-bytestring/issues
    Source repository	head: git clone git://github.com/Soostone/uri-bytestring.git

thanks!
m.

**Comment by MichaelXavier** [comment]
This is fixed in master already. We can push out the updated links on our next release.

**Comment by mf59816** [comment]
Ok, thanks.  (I was just asking because I vaguely remember there being a difference between the meta data in the cabal package and on hackage.  You somehow can change one without the other, and I thought maybe that's what happened.  You can close this ticket.)
