### ISSUE TITLE
URI to Request

### ISSUE THREAD

**Issue by reactormonk** [Soostone/uri-bytestring#34]
I've built this, but didn't use it in the end, not sure where to contribute it. https://gist.github.com/180b46303eeb96e74b95c12ea424b83f

**Comment by MichaelXavier** [comment]
It would possibly make sense to contribute something like this to the request library in question. It wouldn't be appropriate for uri-bytestring to take request as a dependency for this. Interestingly enough, all the major http client libraries today that I know of parse URIs as strings and are likely slower for it. I'm not sure if anyone has lobbied to have uri-bytestring as a dependency and to parse bytestrings instead.
