### ISSUE TITLE
Unexpected normalizeURIRef behavior

### ISSUE THREAD

**Issue by centromere** [Soostone/uri-bytestring#41]
The documentation [says](https://www.stackage.org/haddock/lts-9.6/uri-bytestring-0.2.3.3/URI-ByteString.html#t:URINormalizationOptions):

    If the path is empty, set it to /

However, this is not what happens:

```
λ> normalizeURIRef' aggressiveNormalization <$> parseURI laxURIParserOptions "http://google.com"
Right "http://google.com/"
λ> normalizeURIRef' aggressiveNormalization <$> parseURI laxURIParserOptions "http://google.com/"
Right "http://google.com"
```

**Comment by MichaelXavier** [comment]
Released at 0.3.0.1
