### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by tvh** [Soostone/uri-bytestring#8]
Are there any plans to put this on Stackage? I think this library is already a vast improvement in terms of design over `network-uri`. Having it on Stackage would maybe give it some traction.

**Comment by MichaelXavier** [comment]
PR is pending over [here](https://github.com/fpco/stackage/pull/618). Will close this when that goes through.

**Comment by MichaelXavier** [comment]
That was merged, so it should show up in the nightlies soon.
