### ISSUE TITLE
Test suite missing files

### ISSUE THREAD

**Issue by snoyberg** [Soostone/uri-bytestring#9]
```
test/Main.hs:6:8:
    Could not find module ‘URI.ByteStringTests’
    Perhaps you meant
      URI.ByteString.Lens
      URI.ByteString.Lens
      URI.ByteString.Types
    Use -v to see a list of the files searched for.
```

**Comment by dmjio** [comment]
@snoyberg, @MichaelXavier, yea getting same.

```bash
In-place registering uri-bytestring-0.1.2...
Preprocessing test suite 'test' for uri-bytestring-0.1.2...

test/Main.hs:6:8:
    Could not find module ‘URI.ByteStringTests’
    Perhaps you meant
      URI.ByteString.Lens
      URI.ByteString.Types
      URI.ByteString (from uri-bytestring-0.1.2@uriby_GOugzPWMj4D00xuFWOosT5)
    Use -v to see a list of the files searched for.
builder for ‘/nix/store/6pi92mdym9pl6kkks0m4a82x238isx70-haskell-uri-bytestring-0.1.2.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/j4aisl2vdiwa1s8w28dr1dyj8lwdf8vc-haskell-bloodhound-0.6.0.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/j4aisl2vdiwa1s8w28dr1dyj8lwdf8vc-haskell-bloodhound-0.6.0.0.drv’ failed
```

**Comment by MichaelXavier** [comment]
Thanks guys. I'll check this out tonight. I'm sure its an easy fix.

**Comment by dmjio** [comment]
@MichaelXavier, cool thanks !

**Comment by MichaelXavier** [comment]
Actually, I can't seem to reproduce this and not sure why this would happen. The test-suite specifies a source dir of test, and ther

**Comment by MichaelXavier** [comment]
Whoops. Didn't mean for that to close. It looks like I was forgetting other-modules in the test section. I'm not sure of the setup you folks are using, but are you able to test the git repo and see if this fixed it?

**Comment by dmjio** [comment]
Yea, I can confirm it's in the git repo, in fact I think it always was, just not sure it made it to the tarball on the call of `cabal sdist`. Just speculating.

**Comment by MichaelXavier** [comment]
Oh, no I mean I updated the .cabal file to now include the missing modules. So if you clone the repo, sdist and then run your process against that I think it should work.

**Comment by dmjio** [comment]
Oh, ah. I see, yea perfect. It works locally for me now. Cheers !

**Comment by MichaelXavier** [comment]
This is up on hackage as 0.1.3.

**Comment by snoyberg** [comment]
Thanks!
